Solution
mate-academy/react_sum pull request #103
Opened 2020-06-23 14:04 UTC by V2473

[DEMO LINK](https://V2473.github.io/react_sum/)

2020-06-24 03:21 UTC, coroboX approved these changes

2020-06-24 08:46 UTC, danheim requested changes

2020-06-24 08:46 UTC, danheim commented on src/components/Sum.js
> +const Sum = (a, b) => `Sum of ${a} and ${b} is ${a + b}`;
Это должен быть компонент который рендерит тег с текстом внутри

2020-06-25 06:29 UTC, danheim approved these changes

2025-07-18 15:03 UTC, closed without merging