Solution
mate-academy/react_sum pull request #1049
Opened 2022-09-01 06:19 UTC by ostUp

[DEMO LINK](https://ostUp.github.io/react_sum/)

2022-09-06 09:43 UTC, Roman-Artiukh commented
![image](https://user-images.githubusercontent.com/108989549/188602588-74e10b39-cb9d-412e-b367-1c59b4431a41.png)
last line is extra))

2022-09-06 14:07 UTC, AndriiRut requested changes

2022-09-06 14:07 UTC, AndriiRut commented on src/components/Sum.jsx
> +    </>
```suggestion
      <p>
        {`Sum of ${a} and ${b} is ${a + b}`}
      </p>
```
don't need of React.Component here.
whatever you do, your component must return only one parent element(div, span, p, `<>` and etc.). No mater how many elements are in it, The parent element should be only the one! and here you already have one the `<p>`

2022-09-07 08:22 UTC, AndriiRut approved these changes
🚀

2023-03-22 18:05 UTC, closed without merging