done
mate-academy/react_sum pull request #1119
Opened 2022-09-21 15:51 UTC by p-omogit-e

[DEMO LINK](https://<your_account>.github.io/react_sum/)

2022-09-22 10:51 UTC, alexandra-protyanova requested changes
U demo doesn't work, because you need to pass your name there

2022-09-22 11:07 UTC, p-omogit-e commented
> U demo doesn't work, because you need to pass your name there

sorry, I changed file, but copied wronf link, edited now

2022-09-24 08:48 UTC, SanyaBratashchuk requested changes
Doesn't work
![image](https://user-images.githubusercontent.com/97547824/192089229-ecb7f325-6ff2-4cfb-815c-39672b679999.png)

2022-10-07 16:32 UTC, AlisaVlasova approved these changes

2025-12-17 21:25 UTC, closed without merging