solution
mate-academy/react_sum pull request #1706
Opened 2023-04-26 12:07 UTC by kq333

[DEMO LINK](https://kq333.github.io/react_sum/)

2023-04-27 06:56 UTC, d-wasilewski requested changes

2023-04-27 06:56 UTC, d-wasilewski commented on src/App.jsx
> +    />
checklist 1

2023-04-27 06:56 UTC, d-wasilewski commented on src/components/Sum.jsx
> +      {a + b}
checklist 2

2023-04-27 08:52 UTC, d-wasilewski requested changes

2023-04-27 08:52 UTC, d-wasilewski commented on src/components/Sum.jsx
> +export default Sum;
you dont have to export `default` when you import it with { }, that;s why checks fail

2023-04-27 08:52 UTC, d-wasilewski commented on src/components/Sum.jsx
> +  </>
you don't need this fragment wrapper here

2023-04-27 09:05 UTC, d-wasilewski requested changes

2023-04-27 09:05 UTC, d-wasilewski commented on src/components/Sum.jsx
> +export default Sum;
```suggestion
export Sum;
```

2023-04-27 09:29 UTC, d-wasilewski requested changes

2023-04-27 09:29 UTC, d-wasilewski commented on src/components/Sum.jsx
> +export default Sum;
fix the test

2023-04-28 12:49 UTC, kasiakubisiak approved these changes

2023-10-03 20:32 UTC, closed without merging