add task solution React_sum
mate-academy/react_sum pull request #1893
Opened 2023-06-28 16:28 UTC by TamaraShukalo

[DEMO LINK](https://TamaraShukalo.github.io/react_sum/)

2023-06-28 17:53 UTC, outofs requested changes
GW. But need some changes.

2023-06-28 17:56 UTC, outofs requested changes

2023-06-28 17:56 UTC, outofs commented on src/components/Sum/Sum.jsx
> +  <>
You don't need this `<></>` wrapper, because your component has only one `<p><p/>` tag. Maybe that's a reason why  some tests are failed

2023-06-29 07:21 UTC, tetiana-ivanchenko approved these changes

2024-03-25 08:26 UTC, closed without merging