Develop
mate-academy/react_sum pull request #2036
Opened 2023-08-19 08:50 UTC by Dolnys

[DEMO LINK](https://Dolnys.github.io/react_sum/)

2023-08-21 06:34 UTC, choeqq approved these changes

2023-08-21 06:35 UTC, choeqq requested changes

2023-08-21 06:35 UTC, choeqq commented on src/components/Sum/Sum.jsx
[checklist](https://github.com/mate-academy/react_sum/blob/master/checklist.md) point 2

2023-08-21 12:56 UTC, closed without merging

2023-08-22 07:13 UTC, Dolnys commented on src/components/Sum/Sum.jsx
Done

2023-08-22 07:16 UTC, choeqq approved these changes
Looks good to me ✅