Develop
mate-academy/react_sum pull request #849
Opened 2022-05-25 14:41 UTC by yelnikov-andrii

[DEMO LINK](https://yelnikov-andrii.github.io/react_sum/)

2022-05-26 11:35 UTC, Denchepornyuk requested changes

2022-05-26 11:35 UTC, Denchepornyuk commented on src/components/Sum.jsx
> +const Sum = ({ a = 0, b = 0 }) => (
add propTypes for the component

2022-05-28 20:34 UTC, Anna-Tkachenko approved these changes

2022-05-28 20:34 UTC, Anna-Tkachenko commented on src/components/Sum.jsx
> +export default Sum;
use named export to fix the error

2022-05-28 20:34 UTC, Anna-Tkachenko commented on src/components/Sum.jsx
> +const Sum = ({ a, b }) => (
```suggestion
export const Sum = ({ a, b }) => (
```

2024-03-19 14:58 UTC, closed without merging